version: "3.9"

services:
  pixora-minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    container_name: pixora-minio
    restart: always
    volumes:
      - pixora-minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: harshal
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: server --console-address ":9001" /data

  nginx:
    image: nginx:latest
    container_name: nginx-cdn
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - pixora-minio

volumes:
  pixora-minio:
